// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class AchievementsProgressionEventPacket : IPacket<AchievementsProgressionEvent>
{
    public int PacketID => 98;

    public static AchievementsProgressionEvent Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short Value = reader.ReadInt16();

        return new AchievementsProgressionEvent
        {
            Value = Value,
        };
    }

    public static byte[] Serialize(AchievementsProgressionEvent packet)
    {
        FastPacketWriter writer = new(98, 128);

        writer.WriteInt16(packet.Value);

        return writer.BuildPacket();
    }
}

public struct AchievementsProgressionEvent
{
    public short Value;
}
