// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ChestSetPlayerIndexPacket : IPacket<ChestSetPlayerIndex>
{
    public int PacketID => 80;

    public static ChestSetPlayerIndex Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short ChestIndex = reader.ReadInt16();

        return new ChestSetPlayerIndex
        {
            PlayerIndex = PlayerIndex,
            ChestIndex = ChestIndex,
        };
    }

    public static byte[] Serialize(ChestSetPlayerIndex packet)
    {
        FastPacketWriter writer = new(80, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.ChestIndex);

        return writer.BuildPacket();
    }
}

public struct ChestSetPlayerIndex
{
    public byte PlayerIndex;
    public short ChestIndex;
}
