// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ChestInteractPacket : IPacket<ChestInteract>
{
    public int PacketID => 34;

    public static ChestInteract Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte Action = reader.ReadByte();
        short ChestX = reader.ReadInt16();
        short ChestY = reader.ReadInt16();
        short ChestStyle = reader.ReadInt16();
        byte ChestAdditionalValue = reader.ReadByte();

        return new ChestInteract
        {
            Action = Action,
            ChestX = ChestX,
            ChestY = ChestY,
            ChestStyle = ChestStyle,
            ChestAdditionalValue = ChestAdditionalValue,
        };
    }

    public static byte[] Serialize(ChestInteract packet)
    {
        FastPacketWriter writer = new(34, 128);

        writer.WriteByte(packet.Action);
        writer.WriteInt16(packet.ChestX);
        writer.WriteInt16(packet.ChestY);
        writer.WriteInt16(packet.ChestStyle);
        writer.WriteByte(packet.ChestAdditionalValue);

        return writer.BuildPacket();
    }
}

public struct ChestInteract
{
    public byte Action;
    public short ChestX;
    public short ChestY;
    public short ChestStyle;
    public byte ChestAdditionalValue;
}
