// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ChestSetNamePacket : IPacket<ChestSetName>
{
    public int PacketID => 69;

    public static ChestSetName Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ChestIndex = reader.ReadInt16();
        short ChestX = reader.ReadInt16();
        short ChestY = reader.ReadInt16();
        string ChestName = reader.ReadString();

        return new ChestSetName
        {
            ChestIndex = ChestIndex,
            ChestX = ChestX,
            ChestY = ChestY,
            ChestName = ChestName,
        };
    }

    public static byte[] Serialize(ChestSetName packet)
    {
        FastPacketWriter writer = new(69, 128);

        writer.WriteInt16(packet.ChestIndex);
        writer.WriteInt16(packet.ChestX);
        writer.WriteInt16(packet.ChestY);
        writer.WriteString(packet.ChestName);

        return writer.Build();
    }
}

public struct ChestSetName
{
    public short ChestIndex;
    public short ChestX;
    public short ChestY;
    public string ChestName;
}
