// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ChestItemSyncPacket : IPacket<ChestItemSync>
{
    public int PacketID => 32;

    public ChestItemSync Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ChestIndex = reader.ReadInt16();
        byte SlotIndex = reader.ReadByte();
        short ItemStack = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        short ItemType = reader.ReadInt16();

        return new ChestItemSync
        {
            ChestIndex = ChestIndex,
            SlotIndex = SlotIndex,
            ItemStack = ItemStack,
            ItemPrefix = ItemPrefix,
            ItemID = ItemType,
        };
    }

    public byte[] Serialize(ChestItemSync packet)
    {
        FastPacketWriter writer = new(32, 128);

        writer.WriteInt16(packet.ChestIndex);
        writer.WriteByte(packet.SlotIndex);
        writer.WriteInt16(packet.ItemStack);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteInt16(packet.ItemID);

        return writer.BuildPacket();
    }
}

public struct ChestItemSync
{
    public short ChestIndex;
    public byte SlotIndex;
    public byte ItemPrefix;
    public short ItemStack;
    public short ItemID;
}
