// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventReportProgressPacket : IPacket<EventReportProgress>
{
    public int PacketID => 78;

    public static EventReportProgress Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int Progress = reader.ReadInt32();
        int ProgressMax = reader.ReadInt32();
        int Icon = reader.ReadInt32();
        int ProgressWave = reader.ReadInt32();

        return new EventReportProgress
        {
            Progress = Progress,
            ProgressMax = ProgressMax,
            Icon = Icon,
            ProgressWave = ProgressWave,
        };
    }

    public static byte[] Serialize(EventReportProgress packet)
    {
        FastPacketWriter writer = new(78, 128);

        writer.WriteInt32(packet.Progress);
        writer.WriteInt32(packet.ProgressMax);
        writer.WriteInt32(packet.Icon);
        writer.WriteInt32(packet.ProgressWave);

        return writer.Build();
    }
}

public struct EventReportProgress
{
    public int Progress;
    public int ProgressMax;
    public int Icon;
    public int ProgressWave;
}
