// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventDD2AttemptSkipWaitTimePacket : IPacket<EventDD2AttemptSkipWaitTime>
{
    public int PacketID => 143;

    public static EventDD2AttemptSkipWaitTime Deserialize(ReadOnlySpan<byte> data, int offset = 0)
        => new();

    public static byte[] Serialize(EventDD2AttemptSkipWaitTime packet)
    {
        FastPacketWriter writer = new(143, 4);
        return writer.BuildPacket();
    }
}

public struct EventDD2AttemptSkipWaitTime
{
}
