// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventDD2WaveTimeLeftPacket : IPacket<EventDD2WaveTimeLeft>
{
    public int PacketID => 116;

    public static EventDD2WaveTimeLeft Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int Time = reader.ReadInt32();

        return new EventDD2WaveTimeLeft
        {
            Time = Time,
        };
    }

    public static byte[] Serialize(EventDD2WaveTimeLeft packet)
    {
        FastPacketWriter writer = new(116, 128);

        writer.WriteInt32(packet.Time);

        return writer.BuildPacket();
    }
}

public struct EventDD2WaveTimeLeft
{
    public int Time;
}
