// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventDD2TogglePacket : IPacket<EventDD2Toggle>
{
    public int PacketID => 113;

    public static EventDD2Toggle Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();

        return new EventDD2Toggle
        {
            X = X,
            Y = Y,
        };
    }

    public static byte[] Serialize(EventDD2Toggle packet)
    {
        FastPacketWriter writer = new(113, 128);

        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);

        return writer.BuildPacket();
    }
}

public struct EventDD2Toggle
{
    public short X;
    public short Y;
}
