// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventInvokeV1Packet : IPacket<EventInvokeV1>
{
    public int PacketID => 51;

    public static EventInvokeV1 Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte EventType = reader.ReadByte();
        byte EventAdditionalValue = reader.ReadByte();

        return new EventInvokeV1
        {
            EventType = EventType,
            EventAdditionalValue = EventAdditionalValue,
        };
    }

    public static byte[] Serialize(EventInvokeV1 packet)
    {
        FastPacketWriter writer = new(51, 128);

        writer.WriteByte(packet.EventType);
        writer.WriteByte(packet.EventAdditionalValue);

        return writer.BuildPacket();
    }
}

public struct EventInvokeV1
{
    public byte EventType;
    public byte EventAdditionalValue;
}
