// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventDD2WipePacket : IPacket<EventDD2Wipe>
{
    public int PacketID => 114;

    public EventDD2Wipe Deserialize(ReadOnlySpan<byte> data, int offset = 0)
        => new();

    public byte[] Serialize(EventDD2Wipe packet)
    {
        FastPacketWriter writer = new(114, 4);

        return writer.BuildPacket();
    }
}

public struct EventDD2Wipe
{
}
