// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventCreditsOrTransformPacket : IPacket<EventCreditsOrTransform>
{
    public int PacketID => 140;

    public static EventCreditsOrTransform Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte EventType = reader.ReadByte();
        int ExtraValue = reader.ReadInt32();

        return new EventCreditsOrTransform
        {
            EventType = EventType,
            ExtraValue = ExtraValue,
        };
    }

    public static byte[] Serialize(EventCreditsOrTransform packet)
    {
        FastPacketWriter writer = new(140, 128);

        writer.WriteByte(packet.EventType);
        writer.WriteInt32(packet.ExtraValue);

        return writer.BuildPacket();
    }
}

public struct EventCreditsOrTransform
{
    public byte EventType;
    public int ExtraValue;
}
