// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventBirthdayPartyPacket : IPacket<EventBirthdayParty>
{
    public int PacketID => 111;

    public static EventBirthdayParty Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new();
    }

    public static byte[] Serialize(EventBirthdayParty packet)
    {
        FastPacketWriter writer = new(111, 128);

        return writer.Build();
    }
}

public struct EventBirthdayParty
{
}
