// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class EventInvokeV2Packet : IPacket<EventInvokeV2>
{
    public int PacketID => 61;

    public static EventInvokeV2 Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short PlayerIndex = reader.ReadInt16();
        short EventOrBossType = reader.ReadInt16();

        return new EventInvokeV2
        {
            PlayerIndex = PlayerIndex,
            EventOrBossType = EventOrBossType,
        };
    }

    public static byte[] Serialize(EventInvokeV2 packet)
    {
        FastPacketWriter writer = new(61, 128);

        writer.WriteInt16(packet.PlayerIndex);
        writer.WriteInt16(packet.EventOrBossType);

        return writer.BuildPacket();
    }
}

public struct EventInvokeV2
{
    public short PlayerIndex;
    public short EventOrBossType;
}
