// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ItemUpdateShimmerPacket : IPacket<ItemUpdateShimmer>
{
    public int PacketID => 145;

    public static ItemUpdateShimmer Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ItemIndex = reader.ReadInt16();
        NetVector2 Position = reader.ReadNetVector2();
        NetVector2 Velocity = reader.ReadNetVector2();
        short ItemStack = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        byte OwnIgnore = reader.ReadByte();
        short ItemType = reader.ReadInt16();
        bool IsShimmered = reader.ReadBoolean();
        float ShimmerTime = reader.ReadSingle();

        return new ItemUpdateShimmer
        {
            ItemIndex = ItemIndex,
            Position = Position,
            Velocity = Velocity,
            ItemStack = ItemStack,
            ItemPrefix = ItemPrefix,
            OwnIgnore = OwnIgnore,
            ItemType = ItemType,
            IsShimmered = IsShimmered,
            ShimmerTime = ShimmerTime,
        };
    }

    public static byte[] Serialize(ItemUpdateShimmer packet)
    {
        FastPacketWriter writer = new(145, 128);

        writer.WriteInt16(packet.ItemIndex);
        writer.WriteNetVector2(packet.Position);
        writer.WriteNetVector2(packet.Velocity);
        writer.WriteInt16(packet.ItemStack);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteByte(packet.OwnIgnore);
        writer.WriteInt16(packet.ItemType);
        writer.WriteBoolean(packet.IsShimmered);
        writer.WriteSingle(packet.ShimmerTime);

        return writer.BuildPacket();
    }
}

public struct ItemUpdateShimmer
{
    public short ItemIndex;
    public NetVector2 Position;
    public NetVector2 Velocity;
    public short ItemStack;
    public byte ItemPrefix;
    public byte OwnIgnore;
    public short ItemType;
    public bool IsShimmered;
    public float ShimmerTime;
}
