// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ItemRemoveOwnerPacket : IPacket<ItemRemoveOwner>
{
    public int PacketID => 39;

    public static ItemRemoveOwner Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ItemIndex = reader.ReadInt16();

        return new ItemRemoveOwner
        {
            ItemIndex = ItemIndex,
        };
    }

    public static byte[] Serialize(ItemRemoveOwner packet)
    {
        FastPacketWriter writer = new(39, 128);

        writer.WriteInt16(packet.ItemIndex);

        return writer.BuildPacket();
    }
}

public struct ItemRemoveOwner
{
    public short ItemIndex;
}
