// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCAddBuffPacket : IPacket<NPCAddBuff>
{
    public int PacketID => 53;

    public static NPCAddBuff Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        ushort BuffType = reader.ReadUInt16();
        short BuffTime = reader.ReadInt16();

        return new NPCAddBuff
        {
            NPCIndex = NPCIndex,
            BuffType = BuffType,
            BuffTime = BuffTime,
        };
    }

    public static byte[] Serialize(NPCAddBuff packet)
    {
        FastPacketWriter writer = new(53, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteUInt16(packet.BuffType);
        writer.WriteInt16(packet.BuffTime);

        return writer.BuildPacket();
    }
}

public struct NPCAddBuff
{
    public short NPCIndex;
    public ushort BuffType;
    public short BuffTime;
}
