// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCCatchPacket : IPacket<NPCCatch>
{
    public int PacketID => 70;

    public NPCCatch Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        byte PlayerIndex = reader.ReadByte();

        return new NPCCatch
        {
            NPCIndex = NPCIndex,
            PlayerIndex = PlayerIndex,
        };
    }

    public byte[] Serialize(NPCCatch packet)
    {
        FastPacketWriter writer = new(70, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteByte(packet.PlayerIndex);

        return writer.BuildPacket();
    }
}

public struct NPCCatch
{
    public short NPCIndex;
    public byte PlayerIndex;
}