// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCFishOutPacket : IPacket<NPCFishOut>
{
    public int PacketID => 130;

    public static NPCFishOut Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort TileX = reader.ReadUInt16();
        ushort TileY = reader.ReadUInt16();
        short NPCType = reader.ReadInt16();

        return new NPCFishOut
        {
            TileX = TileX,
            TileY = TileY,
            NPCType = NPCType,
        };
    }

    public static byte[] Serialize(NPCFishOut packet)
    {
        FastPacketWriter writer = new(130, 128);

        writer.WriteUInt16(packet.TileX);
        writer.WriteUInt16(packet.TileY);
        writer.WriteInt16(packet.NPCType);

        return writer.BuildPacket();
    }
}

public struct NPCFishOut
{
    public ushort TileX;
    public ushort TileY;
    public short NPCType;
}
