// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCMoneyPingPacket : IPacket<NPCMoneyPing>
{
    public int PacketID => 92;

    public NPCMoneyPing Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        int ExtraValue = reader.ReadInt32();
        NetVector2 Position = reader.ReadNetVector2();

        return new NPCMoneyPing
        {
            NPCIndex = NPCIndex,
            ExtraValue = ExtraValue,
            Position = Position,
        };
    }

    public byte[] Serialize(NPCMoneyPing packet)
    {
        FastPacketWriter writer = new(92, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteInt32(packet.ExtraValue);
        writer.WriteNetVector2(packet.Position);

        return writer.BuildPacket();
    }
}

public struct NPCMoneyPing
{
    public short NPCIndex;
    public int ExtraValue;
    public NetVector2 Position;
}
