// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCNameAndVariationPacket : IPacket<NPCNameAndVariation>
{
    public int PacketID => 56;

    public static NPCNameAndVariation Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        string Name = reader.ReadString();
        int Variation = reader.ReadInt32();

        return new NPCNameAndVariation
        {
            NPCIndex = NPCIndex,
            Name = Name,
            Variation = Variation,
        };
    }

    public static byte[] Serialize(NPCNameAndVariation packet)
    {
        FastPacketWriter writer = new(56, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteString(packet.Name);
        writer.WriteInt32(packet.Variation);

        return writer.Build();
    }
}

public struct NPCNameAndVariation
{
    public short NPCIndex;
    public string Name;
    public int Variation;
}
