// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCReleasePacket : IPacket<NPCRelease>
{
    public int PacketID => 71;

    public static NPCRelease Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int PositionX = reader.ReadInt32();
        int PositionY = reader.ReadInt32();
        short NPCType = reader.ReadInt16();
        byte NPCStyle = reader.ReadByte();

        return new NPCRelease
        {
            PositionX = PositionX,
            PositionY = PositionY,
            NPCType = NPCType,
            NPCStyle = NPCStyle,
        };
    }

    public static byte[] Serialize(NPCRelease packet)
    {
        FastPacketWriter writer = new(71, 128);

        writer.WriteInt32(packet.PositionX);
        writer.WriteInt32(packet.PositionY);
        writer.WriteInt16(packet.NPCType);
        writer.WriteByte(packet.NPCStyle);

        return writer.BuildPacket();
    }
}

public struct NPCRelease
{
    public int PositionX;
    public int PositionY;
    public short NPCType;
    public byte NPCStyle;
}
