// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCRevengeMarkerRemovePacket : IPacket<NPCRevengeMarkerRemove>
{
    public int PacketID => 127;

    public static NPCRevengeMarkerRemove Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int UniqueID = reader.ReadInt32();

        return new NPCRevengeMarkerRemove
        {
            UniqueID = UniqueID,
        };
    }

    public static byte[] Serialize(NPCRevengeMarkerRemove packet)
    {
        FastPacketWriter writer = new(127, 128);

        writer.WriteInt32(packet.UniqueID);

        return writer.BuildPacket();
    }
}

public struct NPCRevengeMarkerRemove
{
    public int UniqueID;
}
