// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCRequestBuffRemovalPacket : IPacket<NPCRequestBuffRemoval>
{
    public int PacketID => 137;

    public NPCRequestBuffRemoval Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        ushort TargetBuffType = reader.ReadUInt16();

        return new NPCRequestBuffRemoval
        {
            NPCIndex = NPCIndex,
            TargetBuffType = TargetBuffType,
        };
    }

    public byte[] Serialize(NPCRequestBuffRemoval packet)
    {
        FastPacketWriter writer = new(137, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteUInt16(packet.TargetBuffType);

        return writer.BuildPacket();
    }
}

public struct NPCRequestBuffRemoval
{
    public short NPCIndex;
    public ushort TargetBuffType;
}