// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCStrikeByItemPacket : IPacket<NPCStrikeByItem>
{
    public int PacketID => 24;

    public static NPCStrikeByItem Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        byte PlayerIndex = reader.ReadByte();

        return new NPCStrikeByItem
        {
            NPCIndex = NPCIndex,
            PlayerIndex = PlayerIndex,
        };
    }

    public static byte[] Serialize(NPCStrikeByItem packet)
    {
        FastPacketWriter writer = new(24, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteByte(packet.PlayerIndex);

        return writer.Build();
    }
}

public struct NPCStrikeByItem
{
    public short NPCIndex;
    public byte PlayerIndex;
}
