// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCShopUpdatePacket : IPacket<NPCShopUpdate>
{
    public int PacketID => 104;

    public NPCShopUpdate Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte SlotIndex = reader.ReadByte();
        short ItemType = reader.ReadInt16();
        short ItemStack = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        int Value = reader.ReadInt32();
        bool BuyOnce = reader.ReadBoolean();

        return new NPCShopUpdate
        {
            SlotIndex = SlotIndex,
            ItemType = ItemType,
            ItemStack = ItemStack,
            ItemPrefix = ItemPrefix,
            Value = Value,
            BuyOnce = BuyOnce,
        };
    }

    public byte[] Serialize(NPCShopUpdate packet)
    {
        FastPacketWriter writer = new(104, 128);

        writer.WriteByte(packet.SlotIndex);
        writer.WriteInt16(packet.ItemType);
        writer.WriteInt16(packet.ItemStack);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteInt32(packet.Value);
        writer.WriteBoolean(packet.BuyOnce);

        return writer.BuildPacket();
    }
}

public struct NPCShopUpdate
{
    public byte SlotIndex;
    public short ItemType;
    public short ItemStack;
    public byte ItemPrefix;
    public int Value;
    public bool BuyOnce;
}