// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCTravelShopPacket : IPacket<NPCTravelShop>
{
    public int PacketID => 72;

    public static NPCTravelShop Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short[] Items = reader.ReadInt16Array(40);

        return new NPCTravelShop
        {
            Items = Items,
        };
    }

    public static byte[] Serialize(NPCTravelShop packet)
    {
        FastPacketWriter writer = new(72, 128);

        writer.WriteInt16Array(packet.Items);

        return writer.BuildPacket();
    }
}

public struct NPCTravelShop
{
    public short[] Items;
}
