// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class NPCTowersStrengthPacket : IPacket<NPCTowersStrength>
{
    public int PacketID => 101;

    public static NPCTowersStrength Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort SolarStrength = reader.ReadUInt16();
        ushort VortexStrength = reader.ReadUInt16();
        ushort NebulaStrength = reader.ReadUInt16();
        ushort StardustStrength = reader.ReadUInt16();

        return new NPCTowersStrength
        {
            SolarStrength = SolarStrength,
            VortexStrength = VortexStrength,
            NebulaStrength = NebulaStrength,
            StardustStrength = StardustStrength,
        };
    }

    public static byte[] Serialize(NPCTowersStrength packet)
    {
        FastPacketWriter writer = new(101, 128);

        writer.WriteUInt16(packet.SolarStrength);
        writer.WriteUInt16(packet.VortexStrength);
        writer.WriteUInt16(packet.NebulaStrength);
        writer.WriteUInt16(packet.StardustStrength);

        return writer.Build();
    }
}

public struct NPCTowersStrength
{
    public ushort SolarStrength;
    public ushort VortexStrength;
    public ushort NebulaStrength;
    public ushort StardustStrength;
}
