// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PasswordReceiveFromClientPacket : IPacket<PasswordReceiveFromClient>
{
    public int PacketID => 38;

    public PasswordReceiveFromClient Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        string Password = reader.ReadString();

        return new PasswordReceiveFromClient
        {
            Password = Password,
        };
    }

    public byte[] Serialize(PasswordReceiveFromClient packet)
    {
        FastPacketWriter writer = new(38, 32);

        writer.WriteString(packet.Password);

        return writer.BuildPacket();
    }
}

public struct PasswordReceiveFromClient
{
    public string Password;
}
