// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PasswordNotifyClientPacket : IPacket<PasswordNotifyClient>
{
    public int PacketID => 37;

    public static PasswordNotifyClient Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new PasswordNotifyClient
        {
        };
    }

    public static byte[] Serialize(PasswordNotifyClient packet)
    {
        FastPacketWriter writer = new(37, 4);

        return writer.BuildPacket();
    }
}

public struct PasswordNotifyClient
{
}
