// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerTalkNPCPacket : IPacket<PlayerTalkNPC>
{
    public int PacketID => 40;

    public static PlayerTalkNPC Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short NPCIndex = reader.ReadInt16();

        return new PlayerTalkNPC
        {
            PlayerIndex = PlayerIndex,
            NPCIndex = NPCIndex,
        };
    }

    public static byte[] Serialize(PlayerTalkNPC packet)
    {
        FastPacketWriter writer = new(40, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.NPCIndex);

        return writer.BuildPacket();
    }
}

public struct PlayerTalkNPC
{
    public byte PlayerIndex;
    public short NPCIndex;
}
