// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerItemRotationPacket : IPacket<PlayerItemRotation>
{
    public int PacketID => 41;

    public static PlayerItemRotation Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        float Rotation = reader.ReadSingle();
        short Animation = reader.ReadInt16();

        return new PlayerItemRotation
        {
            PlayerIndex = PlayerIndex,
            Rotation = Rotation,
            Animation = Animation,
        };
    }

    public static byte[] Serialize(PlayerItemRotation packet)
    {
        FastPacketWriter writer = new(41, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteSingle(packet.Rotation);
        writer.WriteInt16(packet.Animation);

        return writer.BuildPacket();
    }
}

public struct PlayerItemRotation
{
    public byte PlayerIndex;
    public float Rotation;
    public short Animation;
}
