// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerStealthPacket : IPacket<PlayerStealth>
{
    public int PacketID => 84;

    public PlayerStealth Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        float Stealth = reader.ReadSingle();

        return new PlayerStealth
        {
            PlayerIndex = PlayerIndex,
            Stealth = Stealth,
        };
    }

    public byte[] Serialize(PlayerStealth packet)
    {
        FastPacketWriter writer = new(84, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteSingle(packet.Stealth);

        return writer.BuildPacket();
    }
}

public struct PlayerStealth
{
    public byte PlayerIndex;
    public float Stealth;
}