// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerSetTeamPacket : IPacket<PlayerSetTeam>
{
    public int PacketID => 45;

    public static PlayerSetTeam Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte TeamIndex = reader.ReadByte();

        return new PlayerSetTeam
        {
            PlayerIndex = PlayerIndex,
            TeamIndex = TeamIndex,
        };
    }

    public static byte[] Serialize(PlayerSetTeam packet)
    {
        FastPacketWriter writer = new(45, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.TeamIndex);

        return writer.Build();
    }
}

public struct PlayerSetTeam
{
    public byte PlayerIndex;
    public byte TeamIndex;
}
