// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerZonePacket : IPacket<PlayerZone>
{
    public int PacketID => 36;

    public static PlayerZone Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte Zone1 = reader.ReadByte();
        byte Zone2 = reader.ReadByte();
        byte Zone3 = reader.ReadByte();
        byte Zone4 = reader.ReadByte();
        byte Zone5 = reader.ReadByte();

        return new PlayerZone
        {
            PlayerIndex = PlayerIndex,
            Zone1 = Zone1,
            Zone2 = Zone2,
            Zone3 = Zone3,
            Zone4 = Zone4,
            Zone5 = Zone5,
        };
    }

    public static byte[] Serialize(PlayerZone packet)
    {
        FastPacketWriter writer = new(36, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.Zone1);
        writer.WriteByte(packet.Zone2);
        writer.WriteByte(packet.Zone3);
        writer.WriteByte(packet.Zone4);
        writer.WriteByte(packet.Zone5);

        return writer.BuildPacket();
    }
}

public struct PlayerZone
{
    public byte PlayerIndex;
    public byte Zone1;
    public byte Zone2;
    public byte Zone3;
    public byte Zone4;
    public byte Zone5;
}
