// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerMinionRestPointPacket : IPacket<PlayerMinionRestPoint>
{
    public int PacketID => 99;

    public static PlayerMinionRestPoint Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        NetVector2 Position = reader.ReadNetVector2();

        return new PlayerMinionRestPoint
        {
            PlayerIndex = PlayerIndex,
            Position = Position,
        };
    }

    public static byte[] Serialize(PlayerMinionRestPoint packet)
    {
        FastPacketWriter writer = new(99, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteNetVector2(packet.Position);

        return writer.Build();
    }
}

public struct PlayerMinionRestPoint
{
    public byte PlayerIndex;
    public NetVector2 Position;
}
