// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerSyncPickTilePacket : IPacket<PlayerSyncPickTile>
{
    public int PacketID => 125;

    public static PlayerSyncPickTile Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();
        byte PickDamage = reader.ReadByte();

        return new PlayerSyncPickTile
        {
            PlayerIndex = PlayerIndex,
            TileX = TileX,
            TileY = TileY,
            PickDamage = PickDamage,
        };
    }

    public static byte[] Serialize(PlayerSyncPickTile packet)
    {
        FastPacketWriter writer = new(125, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);
        writer.WriteByte(packet.PickDamage);

        return writer.BuildPacket();
    }
}

public struct PlayerSyncPickTile
{
    public byte PlayerIndex;
    public short TileX;
    public short TileY;
    public byte PickDamage;
}
