// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerAddBuffPacket : IPacket<PlayerAddBuff>
{
    public int PacketID => 55;

    public static PlayerAddBuff Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        ushort BuffType = reader.ReadUInt16();
        int BuffTime = reader.ReadInt32();

        return new PlayerAddBuff
        {
            PlayerIndex = PlayerIndex,
            BuffType = BuffType,
            BuffTime = BuffTime,
        };
    }

    public static byte[] Serialize(PlayerAddBuff packet)
    {
        FastPacketWriter writer = new(55, 16);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteUInt16(packet.BuffType);
        writer.WriteInt32(packet.BuffTime);

        return writer.Build();
    }
}

public struct PlayerAddBuff
{
    public byte PlayerIndex;
    public ushort BuffType;
    public int BuffTime;
}
