// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerLifeHealEffectPacket : IPacket<PlayerLifeHealEffect>
{
    public int PacketID => 66;

    public static PlayerLifeHealEffect Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short Count = reader.ReadInt16();

        return new PlayerLifeHealEffect
        {
            PlayerIndex = PlayerIndex,
            Count = Count,
        };
    }

    public static byte[] Serialize(PlayerLifeHealEffect packet)
    {
        FastPacketWriter writer = new(66, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.Count);

        return writer.BuildPacket();
    }
}

public struct PlayerLifeHealEffect
{
    public byte PlayerIndex;
    public short Count;
}
