// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerDeathPacket : IPacket<PlayerDeath>
{
    public int PacketID => 118;

    public static PlayerDeath Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        NetDeathReason Reason = reader.ReadNetDeathReason();
        short Damage = reader.ReadInt16();
        byte HitDirection = reader.ReadByte();
        bool PvP = reader.ReadByte() != 0;

        return new PlayerDeath
        {
            PlayerIndex = PlayerIndex,
            Reason = Reason,
            Damage = Damage,
            HitDirection = HitDirection,
            PvP = PvP,
        };
    }

    public static byte[] Serialize(PlayerDeath packet)
    {
        FastPacketWriter writer = new(118, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteNetDeathReason(packet.Reason);
        writer.WriteInt16(packet.Damage);
        writer.WriteByte(packet.HitDirection);
        writer.WriteBoolean(packet.PvP);

        return writer.Build();
    }
}

public struct PlayerDeath
{
    public byte PlayerIndex;
    public NetDeathReason Reason;
    public short Damage;
    public byte HitDirection;
    public bool PvP;
}
