// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerLoadoutPacket : IPacket<PlayerLoadout>
{
    public int PacketID => 147;

    public PlayerLoadout Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte LoadoutIndex = reader.ReadByte();

        return new PlayerLoadout
        {
            PlayerIndex = PlayerIndex,
            LoadoutIndex = LoadoutIndex,
        };
    }

    public byte[] Serialize(PlayerLoadout packet)
    {
        FastPacketWriter writer = new(147, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.LoadoutIndex);

        return writer.BuildPacket();
    }
}

public struct PlayerLoadout
{
    public byte PlayerIndex;
    public byte LoadoutIndex;
}