// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerSyncBuffsPacket : IPacket<PlayerSyncBuffs>
{
    public int PacketID => 50;

    public static PlayerSyncBuffs Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte plrIndex = reader.ReadByte();
        ushort[] buffData = reader.ReadUInt16Array(44);

        return new PlayerSyncBuffs
        {
            PlayerIndex = plrIndex,
            BuffData = buffData,
        };
    }

    public static byte[] Serialize(PlayerSyncBuffs packet)
    {
        FastPacketWriter writer = new(50, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteUInt16Array(packet.BuffData);

        return writer.Build();
    }
}

public struct PlayerSyncBuffs
{
    public byte PlayerIndex;
    public ushort[] BuffData;
}
