// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerAnglerQuestPacket : IPacket<PlayerAnglerQuest>
{
    public int PacketID => 74;

    public static PlayerAnglerQuest Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte QuestType = reader.ReadByte();
        bool IsCompleted = reader.ReadBoolean();

        return new PlayerAnglerQuest
        {
            QuestType = QuestType,
            IsCompleted = IsCompleted,
        };
    }

    public static byte[] Serialize(PlayerAnglerQuest packet)
    {
        FastPacketWriter writer = new(74, 8);

        writer.WriteByte(packet.QuestType);
        writer.WriteBoolean(packet.IsCompleted);

        return writer.BuildPacket();
    }
}

public struct PlayerAnglerQuest
{
    public byte QuestType;
    public bool IsCompleted;
}
