// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerRequestWorldInfoPacket : IPacket<PlayerRequestWorldInfo>
{
    public int PacketID => 6;

    public static PlayerRequestWorldInfo Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new PlayerRequestWorldInfo
        {
        };
    }

    public static byte[] Serialize(PlayerRequestWorldInfo packet)
    {
        FastPacketWriter writer = new(6, 128);

        return writer.Build();
    }
}

public struct PlayerRequestWorldInfo
{
}
