// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerSpawnPacket : IPacket<PlayerSpawn>
{
    public int PacketID => 12;

    public static PlayerSpawn Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short SpawnX = reader.ReadInt16();
        short SpawnY = reader.ReadInt16();
        int RespawnTimer = reader.ReadInt32();
        short DeathsPvE = reader.ReadInt16();
        short DeathsPvP = reader.ReadInt16();
        byte SpawnContext = reader.ReadByte();

        return new PlayerSpawn
        {
            PlayerIndex = PlayerIndex,
            SpawnX = SpawnX,
            SpawnY = SpawnY,
            RespawnTimer = RespawnTimer,
            DeathsPvE = DeathsPvE,
            DeathsPvP = DeathsPvP,
            SpawnContext = SpawnContext
        };
    }

    public static byte[] Serialize(PlayerSpawn packet)
    {
        FastPacketWriter writer = new(12, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.SpawnX);
        writer.WriteInt16(packet.SpawnY);
        writer.WriteInt32(packet.RespawnTimer);
        writer.WriteInt16(packet.DeathsPvE);
        writer.WriteInt16(packet.DeathsPvP);
        writer.WriteByte(packet.SpawnContext);

        return writer.Build();
    }
}

public struct PlayerSpawn
{
    public byte PlayerIndex;
    public short SpawnX;
    public short SpawnY;
    public int RespawnTimer;
    public short DeathsPvE;
    public short DeathsPvP;
    public byte SpawnContext;
}
