// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerFinishedConnectionPacket : IPacket<PlayerFinishedConnection>
{
    public int PacketID => 49;

    public static PlayerFinishedConnection Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new PlayerFinishedConnection
        {

        };
    }

    public static byte[] Serialize(PlayerFinishedConnection packet)
    {
        FastPacketWriter writer = new(49, 4);

        return writer.BuildPacket();
    }
}

public struct PlayerFinishedConnection
{
}
