// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerReadProjectileTrackersPacket : IPacket<PlayerReadProjectileTrackers>
{
    public int PacketID => 142;

    public PlayerReadProjectileTrackers Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        NetTrackerData PiggyBank = reader.ReadNetTrackerData();
        NetTrackerData VoidLens = reader.ReadNetTrackerData();

        return new PlayerReadProjectileTrackers
        {
            PlayerIndex = PlayerIndex,
            PiggyBank = PiggyBank,
            VoidLens = VoidLens,
        };
    }

    public byte[] Serialize(PlayerReadProjectileTrackers packet)
    {
        FastPacketWriter writer = new(142, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteNetTrackerData(packet.PiggyBank);
        writer.WriteNetTrackerData(packet.VoidLens);

        return writer.BuildPacket();
    }
}

public struct PlayerReadProjectileTrackers
{
    public byte PlayerIndex;
    public NetTrackerData PiggyBank;
    public NetTrackerData VoidLens;
}
