// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerSyncBuffsPacket : IPacket<PlayerSyncBuffs>
{
    public int PacketID => 50;

    public PlayerSyncBuffs Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort[] buffData = reader.ReadUInt16Array(44);

        return new PlayerSyncBuffs
        {
            BuffData = buffData,
        };
    }

    public byte[] Serialize(PlayerSyncBuffs packet)
    {
        FastPacketWriter writer = new(50, 128);

        writer.WriteUInt16Array(packet.BuffData);

        return writer.BuildPacket();
    }
}

public struct PlayerSyncBuffs
{
    public ushort[] BuffData;
}
