// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerManaPacket : IPacket<PlayerMana>
{
    public int PacketID => 42;

    public static PlayerMana Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short ManaCount = reader.ReadInt16();
        short ManaMax = reader.ReadInt16();

        return new PlayerMana
        {
            PlayerIndex = PlayerIndex,
            ManaCount = ManaCount,
            ManaMax = ManaMax,
        };
    }

    public static byte[] Serialize(PlayerMana packet)
    {
        FastPacketWriter writer = new(42, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.ManaCount);
        writer.WriteInt16(packet.ManaMax);

        return writer.BuildPacket();
    }
}

public struct PlayerMana
{
    public byte PlayerIndex;
    public short ManaCount;
    public short ManaMax;
}
