// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerPlayItemSoundPacket : IPacket<PlayerPlayItemSound>
{
    public int PacketID => 58;

    public static PlayerPlayItemSound Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        float Depth = reader.ReadSingle();

        return new PlayerPlayItemSound
        {
            PlayerIndex = PlayerIndex,
            Depth = Depth,
        };
    }

    public static byte[] Serialize(PlayerPlayItemSound packet)
    {
        FastPacketWriter writer = new(58, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteSingle(packet.Depth);

        return writer.Build();
    }
}

public struct PlayerPlayItemSound
{
    public byte PlayerIndex;
    public float Depth;
}
