// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerItemTeleportPacket : IPacket<PlayerItemTeleport>
{
    public int PacketID => 73;

    public static PlayerItemTeleport Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte TeleportStyle = reader.ReadByte();

        return new PlayerItemTeleport
        {
            TeleportStyle = TeleportStyle,
        };
    }

    public static byte[] Serialize(PlayerItemTeleport packet)
    {
        FastPacketWriter writer = new(73, 128);

        writer.WriteByte(packet.TeleportStyle);

        return writer.BuildPacket();
    }
}

public struct PlayerItemTeleport
{
    public byte TeleportStyle;
}
