// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerNotifyQuestCompletePacket : IPacket<PlayerNotifyQuestComplete>
{
    public int PacketID => 75;

    public static PlayerNotifyQuestComplete Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);
        return new PlayerNotifyQuestComplete
        {
        };
    }

    public static byte[] Serialize(PlayerNotifyQuestComplete packet)
    {
        FastPacketWriter writer = new(75, 4);

        return writer.BuildPacket();
    }
}

public struct PlayerNotifyQuestComplete
{
}
