// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerConsumeItemPacket : IPacket<PlayerConsumeItem>
{
    public int PacketID => 110;

    public static PlayerConsumeItem Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ItemType = reader.ReadInt16();
        short ItemCount = reader.ReadInt16();
        byte PlayerIndex = reader.ReadByte();

        return new PlayerConsumeItem
        {
            ItemType = ItemType,
            ItemCount = ItemCount,
            PlayerIndex = PlayerIndex,
        };
    }

    public static byte[] Serialize(PlayerConsumeItem packet)
    {
        FastPacketWriter writer = new(110, 128);

        writer.WriteInt16(packet.ItemType);
        writer.WriteInt16(packet.ItemCount);
        writer.WriteByte(packet.PlayerIndex);

        return writer.BuildPacket();
    }
}

public struct PlayerConsumeItem
{
    public short ItemType;
    public short ItemCount;
    public byte PlayerIndex;
}
