// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerInfoPacket : IPacket<PlayerInfo>
{
    public int PacketID => 4;

    public static PlayerInfo Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte SkinVariant = reader.ReadByte();
        byte HairID = reader.ReadByte();
        string Name = reader.ReadString();
        byte HairDyeID = reader.ReadByte();
        bool[] AccessoryVisiblity = reader.ReadBooleanArray(10);
        byte MiscVisiblity = reader.ReadByte();
        NetColor HairColor = reader.ReadNetColor();
        NetColor SkinColor = reader.ReadNetColor();
        NetColor EyeColor = reader.ReadNetColor();
        NetColor ShirtColor = reader.ReadNetColor();
        NetColor UnderShirtColor = reader.ReadNetColor();
        NetColor PantsColor = reader.ReadNetColor();
        NetColor ShoeColor = reader.ReadNetColor();
        byte Flags = reader.ReadByte();
        byte Flags2 = reader.ReadByte();
        byte Flags3 = reader.ReadByte();

        return new PlayerInfo
        {
            PlayerIndex = PlayerIndex,
            SkinVariant = SkinVariant,
            HairID = HairID,
            Name = Name,
            HairDyeID = HairDyeID,
            AccessoryVisiblity = AccessoryVisiblity,
            MiscVisiblity = MiscVisiblity,
            HairColor = HairColor,
            SkinColor = SkinColor,
            EyeColor = EyeColor,
            ShirtColor = ShirtColor,
            UnderShirtColor = UnderShirtColor,
            PantsColor = PantsColor,
            ShoeColor = ShoeColor,
            Flags = Flags,
            Flags2 = Flags2,
            Flags3 = Flags3,
        };
    }

    public static byte[] Serialize(PlayerInfo packet)
    {
        FastPacketWriter writer = new(4, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.SkinVariant);
        writer.WriteByte(packet.HairID);
        writer.WriteString(packet.Name);
        writer.WriteByte(packet.HairDyeID);
        writer.WriteBooleanArray(packet.AccessoryVisiblity);
        writer.WriteByte(packet.MiscVisiblity);
        writer.WriteNetColor(packet.HairColor);
        writer.WriteNetColor(packet.SkinColor);
        writer.WriteNetColor(packet.EyeColor);
        writer.WriteNetColor(packet.ShirtColor);
        writer.WriteNetColor(packet.UnderShirtColor);
        writer.WriteNetColor(packet.PantsColor);
        writer.WriteNetColor(packet.ShoeColor);
        writer.WriteByte(packet.Flags);
        writer.WriteByte(packet.Flags2);
        writer.WriteByte(packet.Flags3);

        return writer.Build();
    }
}

public struct PlayerInfo
{
    public byte PlayerIndex;
    public byte SkinVariant;
    public byte HairID;
    public string Name;
    public byte HairDyeID;
    public bool[] AccessoryVisiblity;
    public byte MiscVisiblity;
    public NetColor HairColor;
    public NetColor SkinColor;
    public NetColor EyeColor;
    public NetColor ShirtColor;
    public NetColor UnderShirtColor;
    public NetColor PantsColor;
    public NetColor ShoeColor;
    public byte Flags;
    public byte Flags2;
    public byte Flags3;
}
