// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerActivePacket : IPacket<PlayerActive>
{
    public int PacketID => 14;

    public static PlayerActive Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte State = reader.ReadByte();

        return new PlayerActive
        {
            PlayerIndex = PlayerIndex,
            State = State,
        };
    }

    public static byte[] Serialize(PlayerActive packet)
    {
        FastPacketWriter writer = new(14, 16);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.State);

        return writer.BuildPacket();
    }
}

public struct PlayerActive
{
    public byte PlayerIndex;
    public byte State;
}
