// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerNetIndexPacket : IPacket<PlayerNetIndex>
{
    public int PacketID => 3;

    public static PlayerNetIndex Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        bool SpecialFlag = reader.ReadBoolean();

        return new PlayerNetIndex
        {
            PlayerIndex = PlayerIndex,
            SpecialFlag = SpecialFlag,
        };
    }

    public static byte[] Serialize(PlayerNetIndex packet)
    {
        FastPacketWriter writer = new(3, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteBoolean(packet.SpecialFlag);

        return writer.BuildPacket();
    }
}

public struct PlayerNetIndex
{
    public byte PlayerIndex;
    public bool SpecialFlag;
}
