// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerConnectRequestPacket : IPacket<PlayerConnectRequest>
{
    public int PacketID => 1;

    public static PlayerConnectRequest Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        string Protocol = reader.ReadString();

        return new PlayerConnectRequest
        {
            Protocol = Protocol,
        };
    }

    public static byte[] Serialize(PlayerConnectRequest packet)
    {
        FastPacketWriter writer = new(1, 128);

        writer.WriteString(packet.Protocol);

        return writer.Build();
    }
}

public struct PlayerConnectRequest
{
    public string Protocol;
}
