// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerDodgePacket : IPacket<PlayerDodge>
{
    public int PacketID => 62;

    public PlayerDodge Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte DodgeType = reader.ReadByte();

        return new PlayerDodge
        {
            PlayerIndex = PlayerIndex,
            DodgeType = DodgeType,
        };
    }

    public byte[] Serialize(PlayerDodge packet)
    {
        FastPacketWriter writer = new(62, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.DodgeType);

        return writer.BuildPacket();
    }
}

public struct PlayerDodge
{
    public byte PlayerIndex;
    public byte DodgeType;
}