// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerConnectionPrepareWorldPacket : IPacket<PlayerConnectionPrepareWorld>
{
    public int PacketID => 129;

    public PlayerConnectionPrepareWorld Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new PlayerConnectionPrepareWorld
        {
        };
    }

    public byte[] Serialize(PlayerConnectionPrepareWorld packet)
    {
        FastPacketWriter writer = new(129, 4);
        return writer.BuildPacket();
    }
}

public struct PlayerConnectionPrepareWorld
{
}
