// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class PlayerPvPPacket : IPacket<PlayerPvP>
{
    public int PacketID => 30;

    public PlayerPvP Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        bool IsInPvP = reader.ReadBoolean();

        return new PlayerPvP
        {
            PlayerIndex = PlayerIndex,
            IsInPvP = IsInPvP,
        };
    }

    public byte[] Serialize(PlayerPvP packet)
    {
        FastPacketWriter writer = new(30, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteBoolean(packet.IsInPvP);

        return writer.BuildPacket();
    }
}

public struct PlayerPvP
{
    public byte PlayerIndex;
    public bool IsInPvP;
}