// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class ProjectileKillPacket : IPacket<ProjectileKill>
{
    public int PacketID => 29;

    public static ProjectileKill Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ProjectileIdentity = reader.ReadInt16();
        byte OwnerIndex = reader.ReadByte();

        return new ProjectileKill
        {
            ProjectileIdentity = ProjectileIdentity,
            OwnerIndex = OwnerIndex,
        };
    }

    public static byte[] Serialize(ProjectileKill packet)
    {
        FastPacketWriter writer = new(29, 128);

        writer.WriteInt16(packet.ProjectileIdentity);
        writer.WriteByte(packet.OwnerIndex);

        return writer.BuildPacket();
    }
}

public struct ProjectileKill
{
    public short ProjectileIdentity;
    public byte OwnerIndex;
}
