// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class SignReadPacket : IPacket<SignRead>
{
    public int PacketID => 46;

    public static SignRead Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short SignX = reader.ReadInt16();
        short SignY = reader.ReadInt16();

        return new SignRead
        {
            SignX = SignX,
            SignY = SignY,
        };
    }

    public static byte[] Serialize(SignRead packet)
    {
        FastPacketWriter writer = new(46, 128);

        writer.WriteInt16(packet.SignX);
        writer.WriteInt16(packet.SignY);

        return writer.BuildPacket();
    }
}

public struct SignRead
{
    public short SignX;
    public short SignY;
}
