// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class TEClearAnchorPacket : IPacket<TEClearAnchor>
{
    public int PacketID => 122;

    public static TEClearAnchor Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int TEIndex = reader.ReadInt32();
        byte PlayerIndex = reader.ReadByte();

        return new TEClearAnchor
        {
            TEIndex = TEIndex,
            PlayerIndex = PlayerIndex,
        };
    }

    public static byte[] Serialize(TEClearAnchor packet)
    {
        FastPacketWriter writer = new(122, 128);

        writer.WriteInt32(packet.TEIndex);
        writer.WriteByte(packet.PlayerIndex);

        return writer.BuildPacket();
    }
}

public struct TEClearAnchor
{
    public int TEIndex;
    public byte PlayerIndex;
}
