// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class TEPlaceEntityPacket : IPacket<TEPlaceEntity>
{
    public int PacketID => 87;

    public static TEPlaceEntity Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();
        byte Type = reader.ReadByte();

        return new TEPlaceEntity
        {
            X = X,
            Y = Y,
            Type = Type,
        };
    }

    public static byte[] Serialize(TEPlaceEntity packet)
    {
        FastPacketWriter writer = new(87, 128);

        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);
        writer.WriteByte(packet.Type);

        return writer.BuildPacket();
    }
}

public struct TEPlaceEntity
{
    public short X;
    public short Y;
    public byte Type;
}
