// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class TETryPlaceItemFoodPlatterPacket : IPacket<TETryPlaceItemFoodPlatter>
{
    public int PacketID => 133;

    public static TETryPlaceItemFoodPlatter Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();
        short ItemType = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        short ItemStack = reader.ReadInt16();

        return new TETryPlaceItemFoodPlatter
        {
            X = X,
            Y = Y,
            ItemType = ItemType,
            ItemPrefix = ItemPrefix,
            ItemStack = ItemStack,
        };
    }

    public static byte[] Serialize(TETryPlaceItemFoodPlatter packet)
    {
        FastPacketWriter writer = new(133, 128);

        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);
        writer.WriteInt16(packet.ItemType);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteInt16(packet.ItemStack);

        return writer.BuildPacket();
    }
}

public struct TETryPlaceItemFoodPlatter
{
    public short X;
    public short Y;
    public short ItemType;
    public byte ItemPrefix;
    public short ItemStack;
}
