// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class TETryPlaceItemItemFramePacket : IPacket<TETryPlaceItemItemFrame>
{
    public int PacketID => 89;

    public TETryPlaceItemItemFrame Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();
        short ItemNetID = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        short ItemStack = reader.ReadInt16();

        return new TETryPlaceItemItemFrame
        {
            X = X,
            Y = Y,
            ItemNetID = ItemNetID,
            ItemPrefix = ItemPrefix,
            ItemStack = ItemStack,
        };
    }

    public byte[] Serialize(TETryPlaceItemItemFrame packet)
    {
        FastPacketWriter writer = new(89, 128);

        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);
        writer.WriteInt16(packet.ItemNetID);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteInt16(packet.ItemStack);

        return writer.BuildPacket();
    }
}

public struct TETryPlaceItemItemFrame
{
    public short X;
    public short Y;
    public short ItemNetID;
    public byte ItemPrefix;
    public short ItemStack;
}