// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class TETryPlaceItemWeaponsRackPacket : IPacket<TETryPlaceItemWeaponsRack>
{
    public int PacketID => 123;

    public static TETryPlaceItemWeaponsRack Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();
        short ItemType = reader.ReadInt16();
        byte ItemPrefix = reader.ReadByte();
        short ItemStack = reader.ReadInt16();

        return new TETryPlaceItemWeaponsRack
        {
            X = X,
            Y = Y,
            ItemType = ItemType,
            ItemPrefix = ItemPrefix,
            ItemStack = ItemStack,
        };
    }

    public static byte[] Serialize(TETryPlaceItemWeaponsRack packet)
    {
        FastPacketWriter writer = new(123, 128);

        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);
        writer.WriteInt16(packet.ItemType);
        writer.WriteByte(packet.ItemPrefix);
        writer.WriteInt16(packet.ItemStack);

        return writer.BuildPacket();
    }
}

public struct TETryPlaceItemWeaponsRack
{
    public short X;
    public short Y;
    public short ItemType;
    public byte ItemPrefix;
    public short ItemStack;
}
