// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateEmoteBubblePacket : IPacket<VisualCreateEmoteBubble>
{
    public int PacketID => 120;

    public static VisualCreateEmoteBubble Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte EmoteID = reader.ReadByte();

        return new VisualCreateEmoteBubble
        {
            PlayerIndex = PlayerIndex,
            EmoteID = EmoteID,
        };
    }

    public static byte[] Serialize(VisualCreateEmoteBubble packet)
    {
        FastPacketWriter writer = new(120, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.EmoteID);

        return writer.Build();
    }
}

public struct VisualCreateEmoteBubble
{
    public byte PlayerIndex;
    public byte EmoteID;
}
