// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateCombatTextIntPacket : IPacket<VisualCreateCombatTextInt>
{
    public int PacketID => 81;

    public static VisualCreateCombatTextInt Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        NetVector2 Position = reader.ReadNetVector2();
        NetColor NetColor = reader.ReadNetColor();
        int Amount = reader.ReadInt32();

        return new VisualCreateCombatTextInt
        {
            Position = Position,
            NetColor = NetColor,
            Amount = Amount,
        };
    }

    public static byte[] Serialize(VisualCreateCombatTextInt packet)
    {
        FastPacketWriter writer = new(81, 128);

        writer.WriteNetVector2(packet.Position);
        writer.WriteNetColor(packet.NetColor);
        writer.WriteInt32(packet.Amount);

        return writer.BuildPacket();
    }
}

public struct VisualCreateCombatTextInt
{
    public NetVector2 Position;
    public NetColor NetColor;
    public int Amount;
}
