// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateFXPacket : IPacket<VisualCreateFX>
{
    public int PacketID => 112;

    public static VisualCreateFX Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte EffectType = reader.ReadByte();
        int X = reader.ReadInt32();
        int Y = reader.ReadInt32();
        byte ExtraValue1 = reader.ReadByte();
        short ExtraValue2 = reader.ReadInt16();

        return new VisualCreateFX
        {
            EffectType = EffectType,
            X = X,
            Y = Y,
            ExtraValue1 = ExtraValue1,
            ExtraValue2 = ExtraValue2,
        };
    }

    public static byte[] Serialize(VisualCreateFX packet)
    {
        FastPacketWriter writer = new(112, 128);

        writer.WriteByte(packet.EffectType);
        writer.WriteInt32(packet.X);
        writer.WriteInt32(packet.Y);
        writer.WriteByte(packet.ExtraValue1);
        writer.WriteInt16(packet.ExtraValue2);

        return writer.Build();
    }
}

public struct VisualCreateFX
{
    public byte EffectType;
    public int X;
    public int Y;
    public byte ExtraValue1;
    public short ExtraValue2;
}
