// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateLucyMessagePacket : IPacket<VisualCreateLucyMessage>
{
    public int PacketID => 141;

    public static VisualCreateLucyMessage Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte MessageType = reader.ReadByte();
        byte Variation = reader.ReadByte();
        NetVector2 Velocity = reader.ReadNetVector2();
        int X = reader.ReadInt32();
        int Y = reader.ReadInt32();

        return new VisualCreateLucyMessage
        {
            MessageType = MessageType,
            Variation = Variation,
            Velocity = Velocity,
            X = X,
            Y = Y,
        };
    }

    public static byte[] Serialize(VisualCreateLucyMessage packet)
    {
        FastPacketWriter writer = new(141, 128);

        writer.WriteByte(packet.MessageType);
        writer.WriteByte(packet.Variation);
        writer.WriteNetVector2(packet.Velocity);
        writer.WriteInt32(packet.X);
        writer.WriteInt32(packet.Y);

        return writer.Build();
    }
}

public struct VisualCreateLucyMessage
{
    public byte MessageType;
    public byte Variation;
    public NetVector2 Velocity;
    public int X;
    public int Y;
}
