// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateTemporaryAnimationPacket : IPacket<VisualCreateTemporaryAnimation>
{
    public int PacketID => 77;

    public static VisualCreateTemporaryAnimation Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short Type = reader.ReadInt16();
        ushort TileType = reader.ReadUInt16();
        short X = reader.ReadInt16();
        short Y = reader.ReadInt16();

        return new VisualCreateTemporaryAnimation
        {
            Type = Type,
            TileType = TileType,
            X = X,
            Y = Y,
        };
    }

    public static byte[] Serialize(VisualCreateTemporaryAnimation packet)
    {
        FastPacketWriter writer = new(77, 128);

        writer.WriteInt16(packet.Type);
        writer.WriteUInt16(packet.TileType);
        writer.WriteInt16(packet.X);
        writer.WriteInt16(packet.Y);

        return writer.BuildPacket();
    }
}

public struct VisualCreateTemporaryAnimation
{
    public short Type;
    public ushort TileType;
    public short X;
    public short Y;
}
