// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreatePoofOfSmokePacket : IPacket<VisualCreatePoofOfSmoke>
{
    public int PacketID => 106;

    public static VisualCreatePoofOfSmoke Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ulong HalfVector2Value = reader.ReadUInt64();

        return new VisualCreatePoofOfSmoke
        {
            HalfVector2Value = HalfVector2Value,
        };
    }

    public static byte[] Serialize(VisualCreatePoofOfSmoke packet)
    {
        FastPacketWriter writer = new(106, 128);

        writer.WriteUInt64(packet.HalfVector2Value);

        return writer.BuildPacket();
    }
}

public struct VisualCreatePoofOfSmoke
{
    public ulong HalfVector2Value;
}
