// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Structures;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class VisualCreateCombatTextTextPacket : IPacket<VisualCreateCombatTextText>
{
    public int PacketID => 119;

    public VisualCreateCombatTextText Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        NetVector2 Position = reader.ReadNetVector2();
        NetColor NetColor = reader.ReadNetColor();
        NetText Text = reader.ReadNetText();

        return new VisualCreateCombatTextText
        {
            Position = Position,
            NetColor = NetColor,
            Text = Text,
        };
    }

    public byte[] Serialize(VisualCreateCombatTextText packet)
    {
        FastPacketWriter writer = new(119, 128);

        writer.WriteNetVector2(packet.Position);
        writer.WriteNetColor(packet.NetColor);
        writer.WriteNetText(packet.Text);

        return writer.BuildPacket();
    }
}

public struct VisualCreateCombatTextText
{
    public NetVector2 Position;
    public NetColor NetColor;
    public NetText Text;
}
