// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldTimeSyncPacket : IPacket<WorldTimeSync>
{
    public int PacketID => 18;

    public static WorldTimeSync Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte IsDay = reader.ReadByte();
        int Time = reader.ReadInt32();
        short SunModY = reader.ReadInt16();
        short MoonModY = reader.ReadInt16();

        return new WorldTimeSync
        {
            IsDay = IsDay,
            Time = Time,
            SunModY = SunModY,
            MoonModY = MoonModY,
        };
    }

    public static byte[] Serialize(WorldTimeSync packet)
    {
        FastPacketWriter writer = new(18, 128);

        writer.WriteByte(packet.IsDay);
        writer.WriteInt32(packet.Time);
        writer.WriteInt16(packet.SunModY);
        writer.WriteInt16(packet.MoonModY);

        return writer.BuildPacket();
    }
}

public struct WorldTimeSync
{
    public byte IsDay;
    public int Time;
    public short SunModY;
    public short MoonModY;
}
