// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Engine.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldLockSomethingPacket : IPacket<WorldLockSomething>
{
    public int PacketID => 52;

    public static WorldLockSomething Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte TargetType = reader.ReadByte();
        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();

        return new WorldLockSomething
        {
            TargetType = TargetType,
            TileX = TileX,
            TileY = TileY,
        };
    }

    public static byte[] Serialize(WorldLockSomething packet)
    {
        FastPacketWriter writer = new(52, 128);

        writer.WriteByte(packet.TargetType);
        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);

        return writer.Build();
    }
}

public struct WorldLockSomething
{
    public byte TargetType;
    public short TileX;
    public short TileY;
}
