// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldAddLiquidPacket : IPacket<WorldAddLiquid>
{
    public int PacketID => 48;

    public static WorldAddLiquid Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();
        byte LiquidCount = reader.ReadByte();
        byte LiquidType = reader.ReadByte();

        return new WorldAddLiquid
        {
            TileX = TileX,
            TileY = TileY,
            LiquidCount = LiquidCount,
            LiquidType = LiquidType,
        };
    }

    public static byte[] Serialize(WorldAddLiquid packet)
    {
        FastPacketWriter writer = new(48, 128);

        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);
        writer.WriteByte(packet.LiquidCount);
        writer.WriteByte(packet.LiquidType);

        return writer.BuildPacket();
    }
}

public struct WorldAddLiquid
{
    public short TileX;
    public short TileY;
    public byte LiquidCount;
    public byte LiquidType;
}
