// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldCorruptionsPacket : IPacket<WorldCorruptions>
{
    public int PacketID => 57;

    public WorldCorruptions Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte Good = reader.ReadByte();
        byte Evil = reader.ReadByte();
        byte Blood = reader.ReadByte();

        return new WorldCorruptions
        {
            Good = Good,
            Evil = Evil,
            Blood = Blood,
        };
    }

    public byte[] Serialize(WorldCorruptions packet)
    {
        FastPacketWriter writer = new(57, 128);

        writer.WriteByte(packet.Good);
        writer.WriteByte(packet.Evil);
        writer.WriteByte(packet.Blood);

        return writer.BuildPacket();
    }
}

public struct WorldCorruptions
{
    public byte Good;
    public byte Evil;
    public byte Blood;
}