// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldMassWireOperationPacket : IPacket<WorldMassWireOperation>
{
    public int PacketID => 109;

    public static WorldMassWireOperation Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short StartX = reader.ReadInt16();
        short StartY = reader.ReadInt16();
        short EndX = reader.ReadInt16();
        short EndY = reader.ReadInt16();
        byte ToolMode = reader.ReadByte();

        return new WorldMassWireOperation
        {
            StartX = StartX,
            StartY = StartY,
            EndX = EndX,
            EndY = EndY,
            ToolMode = ToolMode,
        };
    }

    public static byte[] Serialize(WorldMassWireOperation packet)
    {
        FastPacketWriter writer = new(109, 128);

        writer.WriteInt16(packet.StartX);
        writer.WriteInt16(packet.StartY);
        writer.WriteInt16(packet.EndX);
        writer.WriteInt16(packet.EndY);
        writer.WriteByte(packet.ToolMode);

        return writer.BuildPacket();
    }
}

public struct WorldMassWireOperation
{
    public short StartX;
    public short StartY;
    public short EndX;
    public short EndY;
    public byte ToolMode;
}
