// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Network.Core.Packets;
using Amethyst.Network.Utilities;

namespace Amethyst.Network.Packets;

public sealed class WorldTileInteractPacket : IPacket<WorldTileInteract>
{
    public int PacketID => 17;

    public static WorldTileInteract Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte Action = reader.ReadByte();
        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();
        short Type = reader.ReadInt16();
        byte Flags = reader.ReadByte();

        return new WorldTileInteract
        {
            Action = Action,
            TileX = TileX,
            TileY = TileY,
            Type = Type,
            Flags = Flags,
        };
    }

    public static byte[] Serialize(WorldTileInteract packet)
    {
        FastPacketWriter writer = new(17, 128);

        writer.WriteByte(packet.Action);
        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);
        writer.WriteInt16(packet.Type);
        writer.WriteByte(packet.Flags);

        return writer.BuildPacket();
    }
}

public struct WorldTileInteract
{
    public byte Action;
    public short TileX;
    public short TileY;
    public short Type;
    public byte Flags;
}
