// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class AchievementsKilledDirectPacket : IPacket<AchievementsKilledDirect>
{
    public int PacketID => 97;

    public AchievementsKilledDirect Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCType = reader.ReadInt16();

        return new AchievementsKilledDirect
        {
            NPCType = NPCType,
        };
    }

    public byte[] Serialize(AchievementsKilledDirect packet)
    {
        FastPacketWriter writer = new(97, 128);

        writer.WriteInt16(packet.NPCType);

        return writer.BuildPacket();
    }
}

public struct AchievementsKilledDirect
{
    public short NPCType;
}
