// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ChatSendTextMultilinePacket : IPacket<ChatSendTextMultiline>
{
    public int PacketID => 107;

    public ChatSendTextMultiline Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        NetColor NetColor = reader.ReadNetColor();
        NetText Text = reader.ReadNetText();
        short WidthLimit = reader.ReadInt16();

        return new ChatSendTextMultiline
        {
            NetColor = NetColor,
            Text = Text,
            WidthLimit = WidthLimit,
        };
    }

    public byte[] Serialize(ChatSendTextMultiline packet)
    {
        FastPacketWriter writer = new(107, 128);

        writer.WriteNetColor(packet.NetColor);
        writer.WriteNetText(packet.Text);
        writer.WriteInt16(packet.WidthLimit);

        return writer.BuildPacket();
    }
}

public struct ChatSendTextMultiline
{
    public NetColor NetColor;
    public NetText Text;
    public short WidthLimit;
}