// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ChestItemSyncPacket : IPacket<ChestItemSync>
{
    public int PacketID => 32;

    public ChestItemSync Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ChestIndex = reader.ReadInt16();
        byte SlotIndexshort = reader.ReadByte();
        ItemStack byte = reader.ReadUNKNOWN();
        ItemPrefix short = reader.ReadUNKNOWN();

        return new ChestItemSync
        {
            ChestIndex = ChestIndex,
            SlotIndexshort = SlotIndexshort,
            byte = byte,
            short = short,
        };
    }

    public byte[] Serialize(ChestItemSync packet)
    {
        FastPacketWriter writer = new(32, 128);

        writer.WriteInt16(packet.ChestIndex);
        writer.WriteByte(packet.SlotIndexshort);
        writer.WriteUNKNOWN(packet.byte);
        writer.WriteUNKNOWN(packet.short);

        return writer.BuildPacket();
    }
}

public struct ChestItemSync
{
    public short ChestIndex;
    public byte SlotIndexshort;
    public ItemStack byte;
    public ItemPrefix short;
}