// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ChestSyncPacket : IPacket<ChestSync>
{
    public int PacketID => 33;

    public ChestSync Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ChestIndex = reader.ReadInt16();
        short ChestX = reader.ReadInt16();
        short ChestYstring? = reader.ReadInt16();

        return new ChestSync
        {
            ChestIndex = ChestIndex,
            ChestX = ChestX,
            ChestYstring? = ChestYstring?,
        };
    }

    public byte[] Serialize(ChestSync packet)
    {
        FastPacketWriter writer = new(33, 128);

        writer.WriteInt16(packet.ChestIndex);
        writer.WriteInt16(packet.ChestX);
        writer.WriteInt16(packet.ChestYstring?);

        return writer.BuildPacket();
    }
}

public struct ChestSync
{
    public short ChestIndex;
    public short ChestX;
    public short ChestYstring?;
}