// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class EventBirthdayPartyPacket : IPacket<EventBirthdayParty>
{
    public int PacketID => 111;

    public EventBirthdayParty Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte ... = reader.ReadByte();

        return new EventBirthdayParty
        {
            ... = ...,
        };
    }

    public byte[] Serialize(EventBirthdayParty packet)
    {
        FastPacketWriter writer = new(111, 128);

        writer.WriteByte(packet....);

        return writer.BuildPacket();
    }
}

public struct EventBirthdayParty
{
    public byte ...;
}