// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ItemOwnerPacket : IPacket<ItemOwner>
{
    public int PacketID => 22;

    public ItemOwner Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short ItemIndex = reader.ReadInt16();
        byte PlayerIndex = reader.ReadByte();

        return new ItemOwner
        {
            ItemIndex = ItemIndex,
            PlayerIndex = PlayerIndex,
        };
    }

    public byte[] Serialize(ItemOwner packet)
    {
        FastPacketWriter writer = new(22, 128);

        writer.WriteInt16(packet.ItemIndex);
        writer.WriteByte(packet.PlayerIndex);

        return writer.BuildPacket();
    }
}

public struct ItemOwner
{
    public short ItemIndex;
    public byte PlayerIndex;
}