// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCCavernMonsterTypePacket : IPacket<NPCCavernMonsterType>
{
    public int PacketID => 136;

    public NPCCavernMonsterType Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort[2,3] NPCTypes = reader.ReadUNKNOWN();

        return new NPCCavernMonsterType
        {
            NPCTypes = NPCTypes,
        };
    }

    public byte[] Serialize(NPCCavernMonsterType packet)
    {
        FastPacketWriter writer = new(136, 128);

        writer.WriteUNKNOWN(packet.NPCTypes);

        return writer.BuildPacket();
    }
}

public struct NPCCavernMonsterType
{
    public ushort[2,3] NPCTypes;
}