// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCGetImmuneTimePacket : IPacket<NPCGetImmuneTime>
{
    public int PacketID => 131;

    public NPCGetImmuneTime Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort NPCIndex = reader.ReadUInt16();
        byte Flags = reader.ReadByte();
        int? Time = reader.ReadUNKNOWN();
        short? FromWho = reader.ReadUNKNOWN();

        return new NPCGetImmuneTime
        {
            NPCIndex = NPCIndex,
            Flags = Flags,
            Time = Time,
            FromWho = FromWho,
        };
    }

    public byte[] Serialize(NPCGetImmuneTime packet)
    {
        FastPacketWriter writer = new(131, 128);

        writer.WriteUInt16(packet.NPCIndex);
        writer.WriteByte(packet.Flags);
        writer.WriteUNKNOWN(packet.Time);
        writer.WriteUNKNOWN(packet.FromWho);

        return writer.BuildPacket();
    }
}

public struct NPCGetImmuneTime
{
    public ushort NPCIndex;
    public byte Flags;
    public int? Time;
    public short? FromWho;
}