// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCKillCountPacket : IPacket<NPCKillCount>
{
    public int PacketID => 83;

    public NPCKillCount Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndex = reader.ReadInt16();
        int KillCount = reader.ReadInt32();

        return new NPCKillCount
        {
            NPCIndex = NPCIndex,
            KillCount = KillCount,
        };
    }

    public byte[] Serialize(NPCKillCount packet)
    {
        FastPacketWriter writer = new(83, 128);

        writer.WriteInt16(packet.NPCIndex);
        writer.WriteInt32(packet.KillCount);

        return writer.BuildPacket();
    }
}

public struct NPCKillCount
{
    public short NPCIndex;
    public int KillCount;
}