// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCMoonLordCountdownPacket : IPacket<NPCMoonLordCountdown>
{
    public int PacketID => 103;

    public NPCMoonLordCountdown Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int MaxCountdown = reader.ReadInt32();
        int CurrentCountdown = reader.ReadInt32();

        return new NPCMoonLordCountdown
        {
            MaxCountdown = MaxCountdown,
            CurrentCountdown = CurrentCountdown,
        };
    }

    public byte[] Serialize(NPCMoonLordCountdown packet)
    {
        FastPacketWriter writer = new(103, 128);

        writer.WriteInt32(packet.MaxCountdown);
        writer.WriteInt32(packet.CurrentCountdown);

        return writer.BuildPacket();
    }
}

public struct NPCMoonLordCountdown
{
    public int MaxCountdown;
    public int CurrentCountdown;
}