// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCPortalGunTeleportPacket : IPacket<NPCPortalGunTeleport>
{
    public int PacketID => 100;

    public NPCPortalGunTeleport Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort NPCIndex = reader.ReadUInt16();
        short TeleportExtraInfo = reader.ReadInt16();
        NetVector2 Position = reader.ReadNetVector2();
        NetVector2 Velocity = reader.ReadNetVector2();

        return new NPCPortalGunTeleport
        {
            NPCIndex = NPCIndex,
            TeleportExtraInfo = TeleportExtraInfo,
            Position = Position,
            Velocity = Velocity,
        };
    }

    public byte[] Serialize(NPCPortalGunTeleport packet)
    {
        FastPacketWriter writer = new(100, 128);

        writer.WriteUInt16(packet.NPCIndex);
        writer.WriteInt16(packet.TeleportExtraInfo);
        writer.WriteNetVector2(packet.Position);
        writer.WriteNetVector2(packet.Velocity);

        return writer.BuildPacket();
    }
}

public struct NPCPortalGunTeleport
{
    public ushort NPCIndex;
    public short TeleportExtraInfo;
    public NetVector2 Position;
    public NetVector2 Velocity;
}