// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class NPCStrikePacket : IPacket<NPCStrike>
{
    public int PacketID => 28;

    public NPCStrike Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short NPCIndexshort = reader.ReadInt16();
        Damage float = reader.ReadUNKNOWN();
        Knockback byte = reader.ReadUNKNOWN();
        HitContext byte = reader.ReadUNKNOWN();

        return new NPCStrike
        {
            NPCIndexshort = NPCIndexshort,
            float = float,
            byte = byte,
            byte = byte,
        };
    }

    public byte[] Serialize(NPCStrike packet)
    {
        FastPacketWriter writer = new(28, 128);

        writer.WriteInt16(packet.NPCIndexshort);
        writer.WriteUNKNOWN(packet.float);
        writer.WriteUNKNOWN(packet.byte);
        writer.WriteUNKNOWN(packet.byte);

        return writer.BuildPacket();
    }
}

public struct NPCStrike
{
    public short NPCIndexshort;
    public Damage float;
    public Knockback byte;
    public HitContext byte;
}