// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerPortalGunTeleportPacket : IPacket<PlayerPortalGunTeleport>
{
    public int PacketID => 96;

    public PlayerPortalGunTeleport Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short TeleportExtraInfo = reader.ReadInt16();
        NetVector2 Position = reader.ReadNetVector2();
        NetVector2 Velocity = reader.ReadNetVector2();

        return new PlayerPortalGunTeleport
        {
            PlayerIndex = PlayerIndex,
            TeleportExtraInfo = TeleportExtraInfo,
            Position = Position,
            Velocity = Velocity,
        };
    }

    public byte[] Serialize(PlayerPortalGunTeleport packet)
    {
        FastPacketWriter writer = new(96, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.TeleportExtraInfo);
        writer.WriteNetVector2(packet.Position);
        writer.WriteNetVector2(packet.Velocity);

        return writer.BuildPacket();
    }
}

public struct PlayerPortalGunTeleport
{
    public byte PlayerIndex;
    public short TeleportExtraInfo;
    public NetVector2 Position;
    public NetVector2 Velocity;
}