// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerUUIDPacket : IPacket<PlayerUUID>
{
    public int PacketID => 68;

    public PlayerUUID Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        string UUID = reader.ReadString();

        return new PlayerUUID
        {
            UUID = UUID,
        };
    }

    public byte[] Serialize(PlayerUUID packet)
    {
        FastPacketWriter writer = new(68, 128);

        writer.WriteString(packet.UUID);

        return writer.BuildPacket();
    }
}

public struct PlayerUUID
{
    public string UUID;
}