// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerMinionAttackNPCPacket : IPacket<PlayerMinionAttackNPC>
{
    public int PacketID => 115;

    public PlayerMinionAttackNPC Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short NPCIndex = reader.ReadInt16();

        return new PlayerMinionAttackNPC
        {
            PlayerIndex = PlayerIndex,
            NPCIndex = NPCIndex,
        };
    }

    public byte[] Serialize(PlayerMinionAttackNPC packet)
    {
        FastPacketWriter writer = new(115, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.NPCIndex);

        return writer.BuildPacket();
    }
}

public struct PlayerMinionAttackNPC
{
    public byte PlayerIndex;
    public short NPCIndex;
}