// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerCountAsHostPacket : IPacket<PlayerCountAsHost>
{
    public int PacketID => 139;

    public PlayerCountAsHost Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        bool IsHost = reader.ReadBoolean();

        return new PlayerCountAsHost
        {
            PlayerIndex = PlayerIndex,
            IsHost = IsHost,
        };
    }

    public byte[] Serialize(PlayerCountAsHost packet)
    {
        FastPacketWriter writer = new(139, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteBoolean(packet.IsHost);

        return writer.BuildPacket();
    }
}

public struct PlayerCountAsHost
{
    public byte PlayerIndex;
    public bool IsHost;
}