// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerRequestSectionPacket : IPacket<PlayerRequestSection>
{
    public int PacketID => 8;

    public PlayerRequestSection Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int TileX = reader.ReadInt32();
        int TileY = reader.ReadInt32();

        return new PlayerRequestSection
        {
            TileX = TileX,
            TileY = TileY,
        };
    }

    public byte[] Serialize(PlayerRequestSection packet)
    {
        FastPacketWriter writer = new(8, 128);

        writer.WriteInt32(packet.TileX);
        writer.WriteInt32(packet.TileY);

        return writer.BuildPacket();
    }
}

public struct PlayerRequestSection
{
    public int TileX;
    public int TileY;
}