// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerNebulaLevelUpPacket : IPacket<PlayerNebulaLevelUp>
{
    public int PacketID => 102;

    public PlayerNebulaLevelUp Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        ushort Type = reader.ReadUInt16();
        NetVector2 Position = reader.ReadNetVector2();

        return new PlayerNebulaLevelUp
        {
            PlayerIndex = PlayerIndex,
            Type = Type,
            Position = Position,
        };
    }

    public byte[] Serialize(PlayerNebulaLevelUp packet)
    {
        FastPacketWriter writer = new(102, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteUInt16(packet.Type);
        writer.WriteNetVector2(packet.Position);

        return writer.BuildPacket();
    }
}

public struct PlayerNebulaLevelUp
{
    public byte PlayerIndex;
    public ushort Type;
    public NetVector2 Position;
}