// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerLifePacket : IPacket<PlayerLife>
{
    public int PacketID => 16;

    public PlayerLife Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        short LifeCount = reader.ReadInt16();
        short LifeMax = reader.ReadInt16();

        return new PlayerLife
        {
            PlayerIndex = PlayerIndex,
            LifeCount = LifeCount,
            LifeMax = LifeMax,
        };
    }

    public byte[] Serialize(PlayerLife packet)
    {
        FastPacketWriter writer = new(16, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt16(packet.LifeCount);
        writer.WriteInt16(packet.LifeMax);

        return writer.BuildPacket();
    }
}

public struct PlayerLife
{
    public byte PlayerIndex;
    public short LifeCount;
    public short LifeMax;
}