// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerTownNPCQuestsStatsPacket : IPacket<PlayerTownNPCQuestsStats>
{
    public int PacketID => 76;

    public PlayerTownNPCQuestsStats Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        int AnglerQuests = reader.ReadInt32();
        int GolferScore = reader.ReadInt32();

        return new PlayerTownNPCQuestsStats
        {
            PlayerIndex = PlayerIndex,
            AnglerQuests = AnglerQuests,
            GolferScore = GolferScore,
        };
    }

    public byte[] Serialize(PlayerTownNPCQuestsStats packet)
    {
        FastPacketWriter writer = new(76, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteInt32(packet.AnglerQuests);
        writer.WriteInt32(packet.GolferScore);

        return writer.BuildPacket();
    }
}

public struct PlayerTownNPCQuestsStats
{
    public byte PlayerIndex;
    public int AnglerQuests;
    public int GolferScore;
}