// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerConnectionPrepareWorldPacket : IPacket<PlayerConnectionPrepareWorld>
{
    public int PacketID => 129;

    public PlayerConnectionPrepareWorld Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte ... = reader.ReadByte();

        return new PlayerConnectionPrepareWorld
        {
            ... = ...,
        };
    }

    public byte[] Serialize(PlayerConnectionPrepareWorld packet)
    {
        FastPacketWriter writer = new(129, 128);

        writer.WriteByte(packet....);

        return writer.BuildPacket();
    }
}

public struct PlayerConnectionPrepareWorld
{
    public byte ...;
}