// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Structures;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerDisconnectPacket : IPacket<PlayerDisconnect>
{
    public int PacketID => 2;

    public PlayerDisconnect Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        NetText Reason = reader.ReadNetText();

        return new PlayerDisconnect
        {
            Reason = Reason,
        };
    }

    public byte[] Serialize(PlayerDisconnect packet)
    {
        FastPacketWriter writer = new(2, 128);

        writer.WriteNetText(packet.Reason);

        return writer.BuildPacket();
    }
}

public struct PlayerDisconnect
{
    public NetText Reason;
}
