// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerRequestWorldInfoPacket : IPacket<PlayerRequestWorldInfo>
{
    public int PacketID => 6;

    public PlayerRequestWorldInfo Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);



        return new PlayerRequestWorldInfo
        {

        };
    }

    public byte[] Serialize(PlayerRequestWorldInfo packet)
    {
        FastPacketWriter writer = new(6, 128);



        return writer.BuildPacket();
    }
}

public struct PlayerRequestWorldInfo
{

}