// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerFinishedConnectionPacket : IPacket<PlayerFinishedConnection>
{
    public int PacketID => 49;

    public PlayerFinishedConnection Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        return new PlayerFinishedConnection
        {

        };
    }

    public byte[] Serialize(PlayerFinishedConnection packet)
    {
        FastPacketWriter writer = new(49, 4);

        return writer.BuildPacket();
    }
}

public struct PlayerFinishedConnection
{
}
