// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerSyncBuffsPacket : IPacket<PlayerSyncBuffs>
{
    public int PacketID => 50;

    public PlayerSyncBuffs Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort[] buffData = reader.ReadUNKNOWN();

        return new PlayerSyncBuffs
        {
            buffData = buffData,
        };
    }

    public byte[] Serialize(PlayerSyncBuffs packet)
    {
        FastPacketWriter writer = new(50, 128);

        writer.WriteUNKNOWN(packet.buffData);

        return writer.BuildPacket();
    }
}

public struct PlayerSyncBuffs
{
    public ushort[] buffData;
}