// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Structures;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerDeathPacket : IPacket<PlayerDeath>
{
    public int PacketID => 118;

    public PlayerDeath Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        NetDeathReason Reason = reader.ReadNetDeathReason();
        short Damage = reader.ReadInt16();
        byte HitDirectionbool = reader.ReadByte();

        return new PlayerDeath
        {
            PlayerIndex = PlayerIndex,
            Reason = Reason,
            Damage = Damage,
            HitDirectionbool = HitDirectionbool,
        };
    }

    public byte[] Serialize(PlayerDeath packet)
    {
        FastPacketWriter writer = new(118, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteNetDeathReason(packet.Reason);
        writer.WriteInt16(packet.Damage);
        writer.WriteByte(packet.HitDirectionbool);

        return writer.BuildPacket();
    }
}

public struct PlayerDeath
{
    public byte PlayerIndex;
    public NetDeathReason Reason;
    public short Damage;
    public byte HitDirectionbool;
}
