// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerUpdatePacket : IPacket<PlayerUpdate>
{
    public int PacketID => 13;

    public PlayerUpdate Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte PlayerIndex = reader.ReadByte();
        byte Flags = reader.ReadByte();
        byte Flags2 = reader.ReadByte();
        byte Flags3 = reader.ReadByte();
        byte Flags4 = reader.ReadByte();
        byte SelectedItem = reader.ReadByte();
        NetVector2 Position = reader.ReadNetVector2();
        NetVector2? Velocity = reader.ReadUNKNOWN();
        NetVector2? PotionOriginalPosition = reader.ReadUNKNOWN();
        NetVector2? PotionHomePosition = reader.ReadUNKNOWN();

        return new PlayerUpdate
        {
            PlayerIndex = PlayerIndex,
            Flags = Flags,
            Flags2 = Flags2,
            Flags3 = Flags3,
            Flags4 = Flags4,
            SelectedItem = SelectedItem,
            Position = Position,
            Velocity = Velocity,
            PotionOriginalPosition = PotionOriginalPosition,
            PotionHomePosition = PotionHomePosition,
        };
    }

    public byte[] Serialize(PlayerUpdate packet)
    {
        FastPacketWriter writer = new(13, 128);

        writer.WriteByte(packet.PlayerIndex);
        writer.WriteByte(packet.Flags);
        writer.WriteByte(packet.Flags2);
        writer.WriteByte(packet.Flags3);
        writer.WriteByte(packet.Flags4);
        writer.WriteByte(packet.SelectedItem);
        writer.WriteNetVector2(packet.Position);
        writer.WriteUNKNOWN(packet.Velocity);
        writer.WriteUNKNOWN(packet.PotionOriginalPosition);
        writer.WriteUNKNOWN(packet.PotionHomePosition);

        return writer.BuildPacket();
    }
}

public struct PlayerUpdate
{
    public byte PlayerIndex;
    public byte Flags;
    public byte Flags2;
    public byte Flags3;
    public byte Flags4;
    public byte SelectedItem;
    public NetVector2 Position;
    public NetVector2? Velocity;
    public NetVector2? PotionOriginalPosition;
    public NetVector2? PotionHomePosition;
}