// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class PlayerChestPlaceItemPacket : IPacket<PlayerChestPlaceItem>
{
    public int PacketID => 85;

    public PlayerChestPlaceItem Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short SlotIndex = reader.ReadInt16();

        return new PlayerChestPlaceItem
        {
            SlotIndex = SlotIndex,
        };
    }

    public byte[] Serialize(PlayerChestPlaceItem packet)
    {
        FastPacketWriter writer = new(85, 8);

        writer.WriteInt16(packet.SlotIndex);

        return writer.BuildPacket();
    }
}

public struct PlayerChestPlaceItem
{
    public short SlotIndex;
}
