// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ProjectileKillPortalPacket : IPacket<ProjectileKillPortal>
{
    public int PacketID => 95;

    public ProjectileKillPortal Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort PlayerIndex = reader.ReadUInt16();
        byte AI1Type = reader.ReadByte();

        return new ProjectileKillPortal
        {
            PlayerIndex = PlayerIndex,
            AI1Type = AI1Type,
        };
    }

    public byte[] Serialize(ProjectileKillPortal packet)
    {
        FastPacketWriter writer = new(95, 128);

        writer.WriteUInt16(packet.PlayerIndex);
        writer.WriteByte(packet.AI1Type);

        return writer.BuildPacket();
    }
}

public struct ProjectileKillPortal
{
    public ushort PlayerIndex;
    public byte AI1Type;
}