// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ReadNetModulePacket : IPacket<ReadNetModule>
{
    public int PacketID => 82;

    public ReadNetModule Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        ushort NetModuleType = reader.ReadUInt16();

        return new ReadNetModule
        {
            NetModuleType = NetModuleType,
        };
    }

    public byte[] Serialize(ReadNetModule packet)
    {
        FastPacketWriter writer = new(82, 128);

        writer.WriteUInt16(packet.NetModuleType);

        return writer.BuildPacket();
    }
}

public struct ReadNetModule
{
    public ushort NetModuleType;
}