// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ServerStatusPacket : IPacket<ServerStatus>
{
    public int PacketID => 9;

    public ServerStatus Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int StatusMax = reader.ReadInt32();
        NetText StatusText = reader.ReadNetText();
        byte StatusFlags = reader.ReadByte();

        return new ServerStatus
        {
            StatusMax = StatusMax,
            StatusText = StatusText,
            StatusFlags = StatusFlags,
        };
    }

    public byte[] Serialize(ServerStatus packet)
    {
        FastPacketWriter writer = new(9, 128);

        writer.WriteInt32(packet.StatusMax);
        writer.WriteNetText(packet.StatusText);
        writer.WriteByte(packet.StatusFlags);

        return writer.BuildPacket();
    }
}

public struct ServerStatus
{
    public int StatusMax;
    public NetText StatusText;
    public byte StatusFlags;
}