// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class ShimmerEffectPacket : IPacket<ShimmerEffect>
{
    public int PacketID => 146;

    public ShimmerEffect Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte EffectType = reader.ReadByte();
        NetVector2 ItemShimmerPosition = reader.ReadNetVector2();
        NetVector2 CoinPosition = reader.ReadNetVector2();
        int CoinAmount = reader.ReadInt32();
        int NPCIndex = reader.ReadInt32();

        return new ShimmerEffect
        {
            EffectType = EffectType,
            ItemShimmerPosition = ItemShimmerPosition,
            CoinPosition = CoinPosition,
            CoinAmount = CoinAmount,
            NPCIndex = NPCIndex,
        };
    }

    public byte[] Serialize(ShimmerEffect packet)
    {
        FastPacketWriter writer = new(146, 128);

        writer.WriteByte(packet.EffectType);
        writer.WriteNetVector2(packet.ItemShimmerPosition);
        writer.WriteNetVector2(packet.CoinPosition);
        writer.WriteInt32(packet.CoinAmount);
        writer.WriteInt32(packet.NPCIndex);

        return writer.BuildPacket();
    }
}

public struct ShimmerEffect
{
    public byte EffectType;
    public NetVector2 ItemShimmerPosition;
    public NetVector2 CoinPosition;
    public int CoinAmount;
    public int NPCIndex;
}