// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class SoundPlayPacket : IPacket<SoundPlay>
{
    public int PacketID => 132;

    public SoundPlay Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        NetVector2 Position = reader.ReadNetVector2();
        ushort SoundKey = reader.ReadUInt16();
        byte Flags = reader.ReadByte();
        int? Style = reader.ReadUNKNOWN();
        float? Volume = reader.ReadUNKNOWN();
        float? Pitch = reader.ReadUNKNOWN();

        return new SoundPlay
        {
            Position = Position,
            SoundKey = SoundKey,
            Flags = Flags,
            Style = Style,
            Volume = Volume,
            Pitch = Pitch,
        };
    }

    public byte[] Serialize(SoundPlay packet)
    {
        FastPacketWriter writer = new(132, 128);

        writer.WriteNetVector2(packet.Position);
        writer.WriteUInt16(packet.SoundKey);
        writer.WriteByte(packet.Flags);
        writer.WriteUNKNOWN(packet.Style);
        writer.WriteUNKNOWN(packet.Volume);
        writer.WriteUNKNOWN(packet.Pitch);

        return writer.BuildPacket();
    }
}

public struct SoundPlay
{
    public NetVector2 Position;
    public ushort SoundKey;
    public byte Flags;
    public int? Style;
    public float? Volume;
    public float? Pitch;
}