// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class TENewOrKillPacket : IPacket<TENewOrKill>
{
    public int PacketID => 86;

    public TENewOrKill Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        int EntityID = reader.ReadInt32();
        bool IsCreate = reader.ReadBoolean();
        NetTileEntity TileEntity = reader.ReadUNKNOWN();

        return new TENewOrKill
        {
            EntityID = EntityID,
            IsCreate = IsCreate,
            TileEntity = TileEntity,
        };
    }

    public byte[] Serialize(TENewOrKill packet)
    {
        FastPacketWriter writer = new(86, 128);

        writer.WriteInt32(packet.EntityID);
        writer.WriteBoolean(packet.IsCreate);
        writer.WriteUNKNOWN(packet.TileEntity);

        return writer.BuildPacket();
    }
}

public struct TENewOrKill
{
    public int EntityID;
    public bool IsCreate;
    public NetTileEntity TileEntity;
}