// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class WorldWiringHitSwitchPacket : IPacket<WorldWiringHitSwitch>
{
    public int PacketID => 59;

    public WorldWiringHitSwitch Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();

        return new WorldWiringHitSwitch
        {
            TileX = TileX,
            TileY = TileY,
        };
    }

    public byte[] Serialize(WorldWiringHitSwitch packet)
    {
        FastPacketWriter writer = new(59, 128);

        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);

        return writer.BuildPacket();
    }
}

public struct WorldWiringHitSwitch
{
    public short TileX;
    public short TileY;
}