// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class WorldPaintWallPacket : IPacket<WorldPaintWall>
{
    public int PacketID => 64;

    public WorldPaintWall Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();
        byte IsCoating = reader.ReadByte();
        byte PaintType = reader.ReadByte();

        return new WorldPaintWall
        {
            TileX = TileX,
            TileY = TileY,
            IsCoating = IsCoating,
            PaintType = PaintType,
        };
    }

    public byte[] Serialize(WorldPaintWall packet)
    {
        FastPacketWriter writer = new(64, 128);

        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);
        writer.WriteByte(packet.IsCoating);
        writer.WriteByte(packet.PaintType);

        return writer.BuildPacket();
    }
}

public struct WorldPaintWall
{
    public short TileX;
    public short TileY;
    public byte IsCoating;
    public byte PaintType;
}