// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class WorldSectionPacket : IPacket<WorldSection>
{
    public int PacketID => 10;

    public WorldSection Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        byte ... = reader.ReadByte();

        return new WorldSection
        {
            ... = ...,
        };
    }

    public byte[] Serialize(WorldSection packet)
    {
        FastPacketWriter writer = new(10, 128);

        writer.WriteByte(packet....);

        return writer.BuildPacket();
    }
}

public struct WorldSection
{
    public byte ...;
}