// Code is generated by the Amethyst.PacketGenerator (v1.0.5.0) tool.
// Do not edit this file manually.
#pragma warning disable CA1051

using Amethyst.Server.Network.Core.Packets;
using Amethyst.Server.Network.Utilities;

namespace Amethyst.Server.Network.Packets;

public sealed class WorldToggleGemLockPacket : IPacket<WorldToggleGemLock>
{
    public int PacketID => 105;

    public WorldToggleGemLock Deserialize(ReadOnlySpan<byte> data, int offset = 0)
    {
        FastPacketReader reader = new(data, offset);

        short TileX = reader.ReadInt16();
        short TileY = reader.ReadInt16();
        bool IsOn = reader.ReadBoolean();

        return new WorldToggleGemLock
        {
            TileX = TileX,
            TileY = TileY,
            IsOn = IsOn,
        };
    }

    public byte[] Serialize(WorldToggleGemLock packet)
    {
        FastPacketWriter writer = new(105, 128);

        writer.WriteInt16(packet.TileX);
        writer.WriteInt16(packet.TileY);
        writer.WriteBoolean(packet.IsOn);

        return writer.BuildPacket();
    }
}

public struct WorldToggleGemLock
{
    public short TileX;
    public short TileY;
    public bool IsOn;
}