name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  build-and-publish:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
      
      - name: Parse SemVer from tag
        id: version
        uses: release-kit/semver@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore Amethyst.Server.csproj
        working-directory: ./src

      - name: Build as Library
        run: dotnet build Amethyst.Server.csproj -c Release --no-restore /p:OutputType=Library
        working-directory: ./src

      - name: Pack NuGet package
        run: dotnet pack Amethyst.Server.csproj -c Release --no-build -p:PackageVersion=${{ steps.version.outputs.full }}
        working-directory: ./src

      - name: Push to NuGet (GitHub)
        run: dotnet nuget push ./bin/Release/Amethyst.Server.*.nupkg --api-key ${{ secrets.GITTOKEN }} --source "https://nuget.pkg.github.com/realms-developers/index.json"
        working-directory: ./src

      - name: Push to NuGet
        run: dotnet nuget push ./bin/Release/Amethyst.Server.*.nupkg --api-key ${{ secrets.NUGETTOKEN }} --source "https://api.nuget.org/v3/index.json"
        working-directory: ./src
